spring:
  application:
    name: AUTH-SERVICE
#  security:
#    user:
#      name: admin
#      password: admin123
#      roles: ADMIN
  config:
    import: "optional:configserver:http://localhost:9000"
  datasource:
    url: jdbc:mysql://localhost:3306/authdb?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#server:
#  port: 8081

custom:
  security:
    secret: VGhpcyBpcyB0aGUgSldUIHNlY3JldCBrZXkgZm9yIGltcGxlbWVudGluZyBqd3QgdG9rZW4gc3lzdGVtIGluIGF1dGggc2VydmljZQ==
